#!/usr/bin/env bash

function run {
  local csv="./benchmarks-$1.csv"
  local commit=$(git log -1 | grep -o -E "[0-9a-f]{40}")

  echo "Running time on $1 (sleep $3) $commit"
  find $2 -type f \( -name "*.scala" -or -name "*.java" \) -exec ./bin/dotc -Ysleep $3 -bench "$4" -d out/bench/ {} +
#  | grep -o -E "\d*ms"
  echo "$commit,$1,$3,"
  rm -R ./out/bench/
}

run "collection-strawman" "./collection-strawman/src/main" 0 "/usr/bin/time"
run "collection-strawman" "./collection-strawman/src/main" 1 "/usr/bin/time"

#run "compiler" "./compiler/src" 0 "/usr/bin/time"
#run "compiler" "./compiler/src" 5 "/usr/bin/time"
